### PR TITLE
Fix to include only specific directories and files during cleanup.

### PR DESCRIPTION
**Pull request by gmclelland**
As described in https://github.com/adrianbj/ProcessModuleToolkit/issues/3

I gave it a shot.  Please test and make sure it works ok.  It seems to work on my sites.

Hope that helps.

### CODE REVIEW

**Comment by adrianbj** [comment]
Thanks @gmclelland - your approach is much simpler than mine - I am not sure why I went the way I did initially, but I can't see any reason at the moment to not go with what you have. The only comment I have is whether you actually need to specify the . and non . versions of each.

Wouldn't this suffice:
```
            // only include specific files and folders
            if(strpos($item->getFilename(), 'index-') === false &&
               strpos($item->getFilename(), 'htaccess-') === false &&
               strpos($item->getFilename(), 'wire-') === false)continue;
```
Note that I also removed the . from before `wire-`, just in case there are any wire-3.0.52 etc. 

Any thoughts on this? Am I missing anything?

Thanks again for your help on this - really appreciated!

**Comment by gmclelland** [comment]
I'm not sure why, but I had the following files/directories in several of my sites:
.htaccess-3.0.52.txt
htaccess-3.0.52.txt
.index-3.0.52.php
index-3.0.52.php
.wire-3.0.52/
...and of course the same files with many different version numbers

I think it may because of this commit https://github.com/ryancramerdesign/ProcessWireUpgrade/commit/5333322703f0f47a6d6454e8fdb3107db330eec4#diff-cda13f2293ef4081dcbc3776b0805bffR400

400-404 where the names are changed

Note: I always use the ProcessWireUpgrade module to upgrade my sites.

**Comment by adrianbj** [comment]
Yeah, I understand that, but a `strpos` on `htacccess-` will match both of the these: `htaccess-3.0.42` and `.htaccess-3.0.42` so I think it's ok as I suggested.

Do you agree, or am I missing something still? Sorry a little busy today, so maybe I am ?

**Comment by adrianbj** [comment]
I went ahead and made my simplification because it seems to be working fine here, but let me know if you find any problems with it.

Thanks again for your help in improving this module!

**Comment by gmclelland** [comment]
On a mobile right now, but I think you still need my version instead.  It
needs to match both files(with and without the dot prefix).

Note: it will not match the main .htaccess file.  You don't want that
getting cleaned up.

**Comment by adrianbj** [comment]
Check when you're back at your desk, but we're not using `strpos()` to check against the 0 position, just whether it exists at all, which is why it will match `htaccess-3.0.42` and `.htaccess-3.0.42`, but I would still like you to confirm when you get a chance. The new version is committed, so just check that it is matching what you expect.

Thanks!

**Comment by gmclelland** [comment]
Thanks @adrianbj.  Looks like the changes you made are good.  I just tested the latest update and everything is cleaned up as expected.

**Comment by adrianbj** [comment]
Great - thanks for letting me know!

**Comment by gmclelland** [comment]
One super minor thing I noticed is that the word "toggleAll" is displayed in the list after a cleanup.

Like this:

The following backup items were deleted.

toggleAll
htaccess-3.0.58.txt
index-3.0.56.php
index-3.0.57.php
index-3.0.54.php

**Comment by adrianbj** [comment]
Thanks @gmclelland - fixed in https://github.com/adrianbj/ProcessModuleToolkit/commit/09b437d888c270ffe01f3a80fc5dccab3136e42e

**Pull request merged**
